title: Calvin Aberg
#logo: 
description: Hi there! My name is Calvin and I'm a senior at Rice University studying Statistics, Sport Anlaytics, and Data Science. Feel free to explore some of the ways I've been able to work with data!
show_downloads: true
theme: jekyll-theme-minimal
